spring:
  application:
    name: envoy-manager-service

  datasource:
    url: jdbc:mysql://localhost:3306/envoy_service
    username: 
    password: 

  kafka:
    consumer:
      bootstrap-servers:
      - localhost:9092
      group-id: my-group
      auto-offset-reset: earliest

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      # Ignore the type info sent by the producer
      spring.json.use.type.headers: false
      spring/.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      # Ensure the package is trusted
      spring.json.trusted.packages: "*"
      # mapping by classpath of sender pojo and receiver pojo
      spring.json.type.mapping: "com.project.hems.simulator_service_testing.model.MeterSnapshot:com.project.hems.envoy_manager_service.model.MeterSnapshot"
      # Specify the local class to always use for this consumer
      spring.json.value.default.type: com.project.hems.envoy_manager_service.model.MeterSnapshot

server:
  port: 8081

property:
  config:
    kafka: 
      topic: BATTERY_STATS

logging:
  level:
    '[com.project.hems.envoy_manager_service]': debug