spring:
  application:
    name: envoy-manager-service

  datasource:
    url: jdbc:mysql://localhost:3306/envoy_service
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      bootstrap-servers:
        - localhost:9092
      group-id: raw-energy-readers
      auto-offset-reset: earliest

#we configure this in kafkaConsumerConfig file so here not needed..
#      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#    properties:
#      # Ignore the type info sent by the producer
#      spring.json.use.type.headers: false
#      spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
#      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer


server:
  port: 8087

property:
  config:
    meter-history:
      batch_size: 60
    kafka:
      raw-energy-group-id: raw-energy-readers
      raw-energy-topic: RAW_ENERGY_READINGS
      raw-energy-partition-count: 3

      dispatch-energy-group-id: dispatch-command-readers
      dispatch-energy-topic: ENERGY_DISPATCH_COMMANDS
      dispatch-energy-partition-count: 1

      site-creation-group-id: site-creation-readers
      site-creation-topic: SITE_CREATION_DETAILS
      site-creation-partition-count: 1

      replica-count: 1

logging:
  level:
    '[com.project.hems.envoy_manager_service]': debug